controller_manager:
  ros__parameters:

    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0
    tf_prefix: "ur5"

io_and_status_controller:
  ros__parameters:
    tf_prefix: "ur5"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: ur5tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: ur5tool0
    topic_name: ft_data


joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur5shoulder_pan_joint
      - ur5shoulder_lift_joint
      - ur5elbow_joint
      - ur5wrist_1_joint
      - ur5wrist_2_joint
      - ur5wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur5shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur5shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur5elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur5wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur5wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur5wrist_3_joint: { trajectory: 0.2, goal: 0.1 }


scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur5shoulder_pan_joint
      - ur5shoulder_lift_joint
      - ur5elbow_joint
      - ur5wrist_1_joint
      - ur5wrist_2_joint
      - ur5wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      ur5shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      ur5shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      ur5elbow_joint: { trajectory: 0.2, goal: 0.1 }
      ur5wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      ur5wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      ur5wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: ur5speed_scaling/speed_scaling_factor

forward_velocity_controller:
  ros__parameters:
    joints:
      - ur5shoulder_pan_joint
      - ur5shoulder_lift_joint
      - ur5elbow_joint
      - ur5wrist_1_joint
      - ur5wrist_2_joint
      - ur5wrist_3_joint
    interface_name: velocity

forward_position_controller:
  ros__parameters:
    joints:
      - ur5shoulder_pan_joint
      - ur5shoulder_lift_joint
      - ur5elbow_joint
      - ur5wrist_1_joint
      - ur5wrist_2_joint
      - ur5wrist_3_joint

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: ur5robotiq_85_left_knuckle_joint
    use_effort_interface: true
    use_speed_interface: true

robotiq_activation_controller:
  ros__parameters:
    default: true