<?xml version="1.0" ?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rox">

    <!-- Xacro Arguments-->
    <xacro:arg name="frame_type" default="short"/>
    <xacro:arg name="rox_type" default="argo"/>
    <xacro:arg name="joint_type" default="fixed"/>
    <xacro:arg name="arm_type" default=""/>
    <xacro:arg name="sim" default=""/>

    <xacro:property name="frame" value="$(arg frame_type)"/>
    <xacro:property name="rox_typ" default="$(arg rox_type)"/>
    <xacro:property name="joint_typ" value="$(arg joint_type)"/>
    <xacro:property name="arm" value="$(arg arm_type)"/>
    <xacro:property name="gz" value="$(arg sim)"/>

    <!-- Include xacro files -->
    <xacro:include filename="$(find rox_description)/urdf/xacros/frame.xacro" />
    <xacro:include filename="$(find rox_description)/urdf/xacros/sick_nanoscan.xacro" />

    <!-- Assigning Xacro properties -->
    <xacro:if value="${frame == 'short'}">
        <xacro:property name="frame_len" value="0.0" />
    </xacro:if>

    <xacro:if value="${frame == 'long'}">
        <xacro:property name="frame_len" value="0.13" />
    </xacro:if>

    <!-- Building the robot from here -->
    <link name="base_link" />

    <xacro:rox_base name="base_footprint"  parent="base_link"
        type="${frame}">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:rox_base>

    <!-- Argo drives -->
    <xacro:if value="${rox_typ == 'argo'}">
        <xacro:include filename="$(find rox_description)/urdf/xacros/argo_drive.xacro" />
        <xacro:argo_drive parent="base_footprint"/>
    </xacro:if>

    <!-- Diff drive -->
    <!-- Includes both Trike and Diff -->
    <xacro:if value="${rox_typ == 'diff' or rox_typ == 'trike'}">
        <xacro:include filename="$(find rox_description)/urdf/xacros/diff_drive.xacro" />
        <xacro:trike_drive parent="base_footprint"/>
    </xacro:if>
    
    <!-- Meca drive -->
    <xacro:if value="${rox_typ == 'meca'}">
        <xacro:include filename="$(find rox_description)/urdf/xacros/meca_drive.xacro" />
        <xacro:meca_drive parent="base_footprint"/>
    </xacro:if>

    <!-- Sensors -->
    <!-- Laser scanners -->
    <xacro:sick_nanoscan name="lidar_1" parent="base_footprint">
        <origin rpy="${pi} 0 ${pi/4}" xyz="${0.2995 + frame_len} 0.269 0.19"/>
    </xacro:sick_nanoscan>

    <xacro:sick_nanoscan name="lidar_2" parent="base_footprint">
        <origin rpy="${pi} 0 -${pi - pi/4}" xyz="-${0.2995 + frame_len} -0.269 0.19"/>
    </xacro:sick_nanoscan>

    <xacro:unless value="${arm == ''}">
        <xacro:include filename="$(find rox_description)/urdf/xacros/cabinet.xacro" />
        <xacro:cabinet name="cabinet" parent="base_footprint">
            <origin rpy="0 0 0" xyz="${frame_len} 0 0.33"/>
        </xacro:cabinet>
        <!-- <xacro:include filename="$(find rox_description)/urdf/xacros/$(arg arm).xacro" />
        <xacro:$(arg arm) name="arm" parent="base_footprint">
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </xacro:$(arg arm)> -->
    </xacro:unless>
    <!-- Check if simulation needs to be used -->
    <xacro:if value="${gz == 'use_gz'}">
        <xacro:include filename="$(find rox_description)/urdf/xacros/gazebo.xacro" />
        <xacro:gazebo_plugins />
    </xacro:if>
</robot>
